### ISSUE TITLE
Unable to resolve dependencies 

### ISSUE THREAD

**Issue by Centterm** [ialejandro/filebot-compiler#1]
Hello there,

the script is leaving without any error after: 
`[OK] Downloads Filebot project dependencies...`

Digging a litte bit into the apache-ant-dependencies-xxxxxxx.log figured out that it seems that the dependencies can not be resolved. Here is the full log:

https://pastebin.com/FmqjdXxX

**Comment by ialejandro** [comment]
Hi friend,

I updated the README but I think it wasn't clear. The solution is in the section: Apache Ivy Cache. You need download ```.ivy2/``` directory from my [repo](https://github.com/ialejandro/filebot-compiler/tree/master/.ivy2) and copy in the user's home whos execute the compile script.

You can create a symbolic link, too if you won't copy or move the ```.ivy2``` directory. Like this:
```
[19:30:22 root@ant]:~# ls -la
total 128
drwxr-xr-x  8 root root  4096 Mar  8 10:20 .
drwxr-xr-x 22 root root  4096 Oct  2 18:48 ..
-rw-------  1 root root 31723 Mar  8 10:20 .bash_history
-rw-r--r--  1 root root  3316 Feb 22 09:42 .bashrc
drwxr-xr-x  3 root root  4096 Feb 16 21:34 .cache
drwxr-xr-x  2 root root  4096 Feb 19 18:22 .filebot
-rw-r--r--  1 root root   167 Jan 24 19:38 .gitconfig
drwxr-xr-x  3 root root  4096 Mar  7 15:20 github
lrwxrwxrwx  1 root root    29 Feb 19 08:44 .ivy2 -> github/filebot-compiler/.ivy2
```

I tried with my normal user (I see your pastebin, with username) and I can compile without problems. In this case I move the ```.ivy2``` directory from the repo to ```/home/ivan```. Look:
```
[19:31:39 root@ant]:/home/ivan# ll
total 82464
drwxr-xr-x  8 ivan ivan     4096 Mar  8 18:56 ./
drwxr-xr-x  3 root root     4096 Oct 13 11:54 ../
-rw-------  1 ivan ivan     1419 Mar  8 19:30 .bash_history
-rw-r--r--  1 ivan ivan      220 Oct 13 11:54 .bash_logout
-rw-r--r--  1 ivan ivan     3526 Oct 13 11:54 .bashrc
drwxr-xr-x 12 ivan ivan     4096 Mar  8 18:56 filebot/
drwxr-xr-x  2 ivan ivan     4096 Mar  8 10:19 .filebot/
-rw-r--r--  1 ivan ivan 84373118 Mar  8 18:56 Filebot_4.7.21_(b51cb13).jar
-rwxr-xr-x  1 ivan ivan     6959 Mar  7 23:06 filebot-compiler.sh*
drwxr-xr-x  3 ivan ivan     4096 Feb 16 21:36 .ivy2/
```

Good luck. Any questions write here.

PS: I need resolve the #2 issue. You can download a stable version (works with new APIs THETVDB, etc.) from my repo like: [Filebot_4.7.19_(d3c7028).jar](https://filebot.ialejandro.rocks/Filebot_4.7.19_(d3c7028).jar) if you need rename any content.

**Comment by Centterm** [comment]
Using your precompiled version, I would need to deal with the filebot.sh as my system is set to Java 8. And I want to keep it as simple as possible and like to compile things on my own.

Regarding the cache, was it my failure or just the cache being offline/unreachable. Anyways, if you can find the time, a little bit more verbosity in the script would help ;) 

> I tried with my normal user (I see your pastebin, with username) 

How else would you do this? Which kind of user is preferred? Also, your script loads everything in the top level of the home directory which is kind of messy. Maybe you should rethink about creating one "filebotcompiler" folder where everything is downloaded (except all installed programs obviously).

>move the .ivy2 directory from the repo to /home/ivan. 

I cloned your whole repp and moved your .ivy2 folder to my /home/user/username/.ivy2 
This folder only contains another "cache" folder. But running your script (which is located in my Downloads Folder) still quits with the same error log after "[OK] Downloads Filebot project dependencies..." 

Thank you for helping me on this.

**Comment by Centterm** [comment]
So almost two weeks have passed, any News on this?

**Comment by ialejandro** [comment]
Sorry friend. I'm working and studying too, I need time to fix. I'm thinking about changing everything and using jenkins for CI and only publishing compiles.

Even if you want compile it won't work because the API keys are remove from the original author (#2). I need create new accounts and enter new API keys.

**Comment by Centterm** [comment]
No problem, I just wanted to check if you are still there ;) I would suggest that every user should enter his own api creds during compilation, you could make some kind of cli input.

**Comment by ialejandro** [comment]
If you want a stable version, check this repo: https://github.com/Phoenix09/filebot/releases. I need a lot of time to improve my code...
